version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: profit_income_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mos2025
      POSTGRES_DB: profit_income
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./admin_scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
